name: 1.0.$(Rev:r)

pr: none

trigger:
    branches:
      include:
        - main

schedules:
    - cron: "0 0 * * *"
      always: true
      displayName: Daily build
      branches:
          include:
            - main

parameters:
  - name: src
    displayName: Source system
    type: string
    values:
      - TRAEFIK

    # default: WISNU
  # - name: dst
  #   displayName: Target system
  #   type: string
  #   values:
  #     - TRAEFIK
  #     - STAGING
  #     - WISNU
  #   default: WISNU
  - name: skipConfig  
    displayName: Skip Config
    type: boolean
    default: true


pool:
    vmImage: ubuntu-22.04

variables:
  # registry_name: 'testwisnuregistry'
  # repository_name: 'hello-world'
  # image: 'hello-world'
  
  ${{ if eq(parameters.src, 'TRAEFIK')}}:
      src_container_registry: 'DevOpsGuy'
      src_repository_name: 'traefik'
      src_image: 'traefik'


  # ${{ if eq(parameters.dst, 'WISNU')}}:
  #     dst_resource_group: 'wisnu'
  #     dst_server: 'testdstwisnu'
  #     dst_dbname: 'testdstdb'

steps:

  - task: AzureCLI@2
    displayName: Clean Docker Image
    inputs:
      azureSubscription: 'That DevOps Guy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/scripts/'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: '$(System.DefaultWorkingDirectory)/scripts/clean-up-image.sh'
      arguments: '$(registry_name) $(repository_name) $(image)'

