name: 1.0.$(Rev:r)

pr: none

trigger:
    branches:
      include:
        - main

pool:
    vmImage: ubuntu-latest

variables:
    URL: 
    SENDER: wisnu@clade.ventures
    RECIPIENT: wissnusetiawan@gmail.com
    System.Debug: true

steps:
  - task: AzureCLI@2
    displayName: Send Result Unit Test
    inputs:
      azureSubscription: 'That DevOps Guy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/bash-scripts/'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: '$(System.DefaultWorkingDirectory)/bash-scripts/email-notification-sendgrid.sh'
      arguments: '$(URL) $(SENDER) $(RECIPIENT)'

