name: 1.0.$(Rev:r)

pr: none

trigger:
    branches:
      include:
        - main

pool:
    vmImage: ubuntu-latest

variables:
    container_registry: 'DevOpsGuy'

steps:
  - task: AzureCLI@2
    displayName: Clean Docker Image
    inputs:
      azureSubscription: 'That DevOps Guy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/bash-scripts/'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: '$(System.DefaultWorkingDirectory)/bash-scripts/clean-up-image.sh'
      arguments: '$(container_registry)'

